version: "3.4"

services:
  formik-async-validation:
    container_name: formik-async-validation
    command: "./start.sh"
    build: ./
    image: josephsiefers/formik-async-validation
    volumes:
      - ./:/home/node
      - type: bind
        source: ./node_modules
        target: /tmp/node_modules
        consistency: delagated
    ports:
      - "127.0.0.1:3001:3000"
